Repository NimbleSM/NimbleSM, pull requests merged in 2020-08, with the labels that each got.

#59 Add unit test for projection to face
  src/nimble_contact_entity.h
  src/nimble_contact_interface.h
  src/nimble_contact_manager.cc
  src/nimble_contact_manager.h
  unit_tests/CMakeLists.txt
  unit_tests/projection_node_to_face.cc
Labels: CI, enhancement

#64 Removed *.e from .gitignore
  .gitignore
Labels: bug

#74 Serial implementation of ArborX contact
  src/contact/serial/arborx_serial_contact_manager.cc
  src/contact/serial/arborx_serial_contact_manager.h
  src/nimble_contact_interface.h
  src/nimble_contact_manager.cc
  src/nimble_contact_manager.h
  src/nimble_element.cc
Labels: enhancement

#78 Generalize contact force non kokkos
  src/contact/serial/arborx_serial_contact_manager.cc
  src/nimble_contact_manager.h
Labels: enhancement

#79 Update sphere_plate_contact.exodiff
  test/sphere_plate_contact/sphere_plate_contact.exodiff
Labels: CI, bug

#92 Add Release flag for all the Nimble builds
  .github/workflows/ubuntu-arborx-mpi.yml
  .github/workflows/ubuntu-arborx-serial.yml
  .github/workflows/ubuntu-kokkos-mpi.yml
  .github/workflows/ubuntu-kokkos-serial.yml
  .github/workflows/ubuntu-mpi.yml
  .github/workflows/ubuntu-serial.yml
  .github/workflows/ubuntu-trilinos-mpi.yml
Labels: CI, bug

#87 Add the possibility to specify a suffix to test names
  test/CMakeLists.txt
Labels: CI, enhancement

#98 Added np1/2 name suffixes to tests for all executables / targets
  test/CMakeLists.txt
Labels: CI, enhancement
