Repository NimbleSM/NimbleSM, pull requests merged in 2021-04, with the labels that each got.

#195 Fix comment in header
  src/nimble_macros.h
Labels: bug

#198 Remove repetitive code and place it in the base class.
  src/nimble_block.cc
  src/nimble_block.h
  src/nimble_block_base.cc
  src/nimble_block_base.h
  src/nimble_kokkos_block.cc
  src/nimble_kokkos_block.h
Labels: enhancement

#202 Move CLI parsing
  src/nimble.cc
  src/nimble_defs.h
  src/nimble_kokkos_model_data.cc
  src/nimble_kokkos_model_data.h
  src/nimble_main.cc
  src/nimble_main.h
  src/nimble_model_data.cc
  src/nimble_model_data.h
  src/nimble_model_data_base.h
  src/nimble_parser.h
Labels: enhancement

#204 Rename executable
  src/CMakeLists.txt
  test/CMakeLists.txt
Labels: enhancement

#208 Re-organize test folder (2)
  test/_wip/cylinder_with_hole/CMakeLists.txt
  test/_wip/cylinder_with_hole/cylinder_with_hole.exodiff
  test/_wip/cylinder_with_hole/cylinder_with_hole.g
  test/_wip/cylinder_with_hole/cylinder_with_hole.g.4.0
  test/_wip/cylinder_with_hole/cylinder_with_hole.g.4.1
  test/_wip/cylinder_with_hole/cylinder_with_hole.g.4.2
  test/_wip/cylinder_with_hole/cylinder_with_hole.g.4.3
  test/_wip/cylinder_with_hole/cylinder_with_hole.g.8.0
  test/_wip/cylinder_with_hole/cylinder_with_hole.g.8.1
  test/_wip/cylinder_with_hole/cylinder_with_hole.g.8.2
  test/_wip/cylinder_with_hole/cylinder_with_hole.g.8.3
  test/_wip/cylinder_with_hole/cylinder_with_hole.g.8.4
  test/_wip/cylinder_with_hole/cylinder_with_hole.g.8.5
  test/_wip/cylinder_with_hole/cylinder_with_hole.g.8.6
  test/_wip/cylinder_with_hole/cylinder_with_hole.g.8.7
  test/_wip/cylinder_with_hole/cylinder_with_hole.gold.e
  test/_wip/cylinder_with_hole/cylinder_with_hole.in
  test/_wip/cylinder_with_hole/cylinder_with_hole.jou
  test/_wip/cylinder_with_hole/rve.g
  test/_wip/plate_with_hole_rve/CMakeLists.txt
  test/_wip/plate_with_hole_rve/plate_with_hole_rve.exodiff
  test/_wip/plate_with_hole_rve/plate_with_hole_rve.g
  test/_wip/plate_with_hole_rve/plate_with_hole_rve.g.3.0
  test/_wip/plate_with_hole_rve/plate_with_hole_rve.g.3.1
  test/_wip/plate_with_hole_rve/plate_with_hole_rve.g.3.2
  test/_wip/plate_with_hole_rve/plate_with_hole_rve.gold.e
  test/_wip/plate_with_hole_rve/plate_with_hole_rve.in
  test/_wip/plate_with_hole_rve/plate_with_hole_rve.jou
  test/_wip/plate_with_hole_rve/rve.g
  test/_wip/quasistatic_tension/CMakeLists.txt
  test/_wip/quasistatic_tension/quasistatic_tension.exodiff
  test/_wip/quasistatic_tension/quasistatic_tension.g
  test/_wip/quasistatic_tension/quasistatic_tension.gold.e
  test/_wip/quasistatic_tension/quasistatic_tension.in
  test/_wip/quasistatic_tension/quasistatic_tension.jou
  test/_wip/tiny_fe_squared/CMakeLists.txt
  test/_wip/tiny_fe_squared/tiny_fe_squared.exodiff
  test/_wip/tiny_fe_squared/tiny_fe_squared.g
  test/_wip/tiny_fe_squared/tiny_fe_squared.g.2.0
  test/_wip/tiny_fe_squared/tiny_fe_squared.g.2.1
  test/_wip/tiny_fe_squared/tiny_fe_squared.gold.e
  test/_wip/tiny_fe_squared/tiny_fe_squared.in
  test/_wip/tiny_fe_squared/tiny_fe_squared.jou
  test/_wip/tiny_fe_squared/tiny_fe_squared_rve.g
Labels: CI, enhancement

#212 Cleanup README.md
  README.md
Labels: documentation

#214 Re-organize tests folder
  test/CMakeLists.txt
  test/dynamics/CMakeLists.txt
  test/dynamics/notched_plate_native_hypoelastic/CMakeLists.txt
  test/dynamics/notched_plate_native_hypoelastic/notched_plate_native_hypoelastic.exodiff
  test/dynamics/notched_plate_native_hypoelastic/notched_plate_native_hypoelastic.g
  test/dynamics/notched_plate_native_hypoelastic/notched_plate_native_hypoelastic.g.2.0
  test/dynamics/notched_plate_native_hypoelastic/notched_plate_native_hypoelastic.g.2.1
  test/dynamics/notched_plate_native_hypoelastic/notched_plate_native_hypoelastic.g.4.0
  test/dynamics/notched_plate_native_hypoelastic/notched_plate_native_hypoelastic.g.4.1
  test/dynamics/notched_plate_native_hypoelastic/notched_plate_native_hypoelastic.g.4.2
  test/dynamics/notched_plate_native_hypoelastic/notched_plate_native_hypoelastic.g.4.3
  test/dynamics/notched_plate_native_hypoelastic/notched_plate_native_hypoelastic.gold.e
  test/dynamics/notched_plate_native_hypoelastic/notched_plate_native_hypoelastic.in
  test/dynamics/notched_plate_native_neohookean/CMakeLists.txt
  test/dynamics/notched_plate_native_neohookean/notched_plate_native_neohookean.exodiff
  test/dynamics/notched_plate_native_neohookean/notched_plate_native_neohookean.g
  test/dynamics/notched_plate_native_neohookean/notched_plate_native_neohookean.g.2.0
  test/dynamics/notched_plate_native_neohookean/notched_plate_native_neohookean.g.2.1
  test/dynamics/notched_plate_native_neohookean/notched_plate_native_neohookean.g.4.0
  test/dynamics/notched_plate_native_neohookean/notched_plate_native_neohookean.g.4.1
  test/dynamics/notched_plate_native_neohookean/notched_plate_native_neohookean.g.4.2
  test/dynamics/notched_plate_native_neohookean/notched_plate_native_neohookean.g.4.3
  test/dynamics/notched_plate_native_neohookean/notched_plate_native_neohookean.gold.e
  test/dynamics/notched_plate_native_neohookean/notched_plate_native_neohookean.in
Labels: CI, enhancement

#222 Fix compilation error after refactor.
  src/contact/parallel/bvh_contact_manager.cc
  src/contact/parallel/bvh_contact_manager.h
  src/nimble_contact_entity.cc
  src/nimble_contact_entity.h
  src/nimble_contact_manager.h
  src/nimble_main.cc
Labels: bug

#224 223 Remove redundant code
  src/nimble_kokkos_block_material_interface.cc
  src/nimble_material.cc
  src/nimble_material.h
  src/nimble_rve.cc
  src/nimble_rve.h
  src/nimble_utils.h
  src/nimble_view.h
Labels: enhancement
